### ISSUE TITLE
ToDo リスト

### ISSUE THREAD

**Issue by yoshinrt** [yoshinrt/vsd#6]
https://github.com/yoshinrt/vsd/blob/d8384b364d4e64c81d216c65283831fadc50ae58/todo.txt からの転記．あまりやる気はないw

### vsd_filter

- [ ] 馬力計測スキン
- [ ] img copy & 変形
- [ ] Image をフォントにする
- [ ] builtin コード
- [ ] エラーメッセージ vararg 化
  - [ ] ユーザエラーメッセージ
- [ ] Image にも Draw 系ができるようにする
- [ ] デジタルタコ用に自由範囲をコピーできる ImgDraw を考える
- [ ] スキンエディタ
- [ ] 音声 FFT 解析
  - [ ] 独立ソフト化して，タコログを吐く
  - [ ] ギアの乱れ解析アルゴリズム
- [ ] セクタータイム表示
- [ ] 手動セクタータイム (+自動計測)
- [ ] 強制手動計測
- [ ] Gセンサー・Distance から GPS を補正
- [ ] 設定画面タブ化
- [ ] コントロールライン位置補正
- [ ] サウンドレーサーテクノロジ
- [x] ActiveXObject の callback

### vsdroid

- [ ] OBDII 情報も BT 経由で読む
- [ ] ラップタイムを twitter でつぶやく
- [ ] ベストラップを出したとき，タイム表示をどうするか考える
- [x] GPS も BT 経由で読む
